// Generated by npm run vectors:regenerate. Public test data only.
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

library Phase1Vector {
    address internal constant OWNER = 0xdAD27C5A7e2cb7461d38BFdD4f33Eb08b9e4a4E3;
    bytes32 internal constant ROOT = 0xaceb7168a85e046d2d8867c290ccbf5e5889ed354d0f5165646e4e34f2c2b8d6;
    bytes32 internal constant DIGEST = 0xdd7513221683e5c6bd144a403af87c822f5d5318755a475df75dce90c867a64d;
    bytes internal constant SIGNATURE = hex"12663ee155409f48f2273eed2bf5fe20e27a30f14eda813714f39ba5648012bf76b935683cc50ff5f92a40a1f7d465a35b462fe1ae76c0dc5046987ad95eff1a1c";

    struct Grant {
        address owner;
        uint256 chainId;
        address sessionKey;
        uint256 perTxLimit;
        uint256 budget;
        uint256 windowSeconds;
        uint256 expiry;
        uint256 nonce;
    }

    function grants() internal pure returns (Grant[] memory result) {
        result = new Grant[](3);
        result[0] = Grant(OWNER, 11155111, 0x1111111111111111111111111111111111111111, 10000000000000000, 100000000000000000, 3600, 2000000000, 7);
        result[1] = Grant(OWNER, 84532, 0x2222222222222222222222222222222222222222, 20000000000000000, 200000000000000000, 86400, 2000000100, 8);
        result[2] = Grant(OWNER, 31337, 0x3333333333333333333333333333333333333333, 30000000000000000, 300000000000000000, 600, 2000000200, 9);
    }

    function leaves() internal pure returns (bytes32[] memory result) {
        result = new bytes32[](3);
        result[0] = 0x74e93b147f6570eaf9d17d8b8a4039eaf7fcce825d87ff5ef7cd9caf1db6f431;
        result[1] = 0x00e865e06e2804f94203ee02f58776b5c30d305db7d4d93dac670ef4608110d6;
        result[2] = 0x2c895da20c40c1e83a9efa2fa57869197d3fdc0ddb1bae1fb78a7539478f4f46;
    }

    function proof(uint256 index) internal pure returns (bytes32[] memory result) {
        if (index == 0) {
            result = new bytes32[](1);
            result[0] = 0x5ea5fa73e575c6f3674b3584d2908dbec0a5845eb2c5fe5c531cf025e5ed7dd9;
            return result;
        }
        if (index == 1) {
            result = new bytes32[](2);
            result[0] = 0x2c895da20c40c1e83a9efa2fa57869197d3fdc0ddb1bae1fb78a7539478f4f46;
            result[1] = 0x74e93b147f6570eaf9d17d8b8a4039eaf7fcce825d87ff5ef7cd9caf1db6f431;
            return result;
        }
        if (index == 2) {
            result = new bytes32[](2);
            result[0] = 0x00e865e06e2804f94203ee02f58776b5c30d305db7d4d93dac670ef4608110d6;
            result[1] = 0x74e93b147f6570eaf9d17d8b8a4039eaf7fcce825d87ff5ef7cd9caf1db6f431;
            return result;
        }
        revert("Unknown grant");
    }
}
