import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { parse } from 'dotenv';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import type { Hex } from 'viem';
import { buildMerkleTree, grantLeaf, mandateDigest, signMandate } from '../src/core/index.js';
import { vectorGrants } from '../test/vector-inputs.js';

async function main() {
  const envPath = fileURLToPath(new URL('../../.env', import.meta.url));
  const original = await readFile(envPath, 'utf8').catch((error: NodeJS.ErrnoException) => {
    if (error.code === 'ENOENT') return '';
    throw error;
  });
  // Rotate only the dedicated fixture key. Preserve other environment entries.
  const retained = original.replace(/^[\t ]*(?:export[\t ]+)?TEST_VECTOR_KEY[\t ]*=.*(?:\r?\n|$)/gm, '');
  await writeFile(envPath, `${retained}${retained.endsWith('\n') || !retained ? '' : '\n'}TEST_VECTOR_KEY=${generatePrivateKey()}\n`, { mode: 0o600 });
  await chmod(envPath, 0o600);
  // Signing keys are read from .env, never embedded in source or public fixtures.
  const key = parse(await readFile(envPath, 'utf8')).TEST_VECTOR_KEY as Hex;
  const account = privateKeyToAccount(key);
  const grants = vectorGrants(account.address);
  const tree = buildMerkleTree(grants);
  const vector = {
    owner: account.address,
    grants,
    leaves: grants.map(grantLeaf),
    proofs: grants.map(grant => tree.getProof(grant)),
    root: tree.root,
    digest: mandateDigest(tree.root),
    signature: await signMandate(tree.root, account),
  };
  const vectorsDir = new URL('../test/vectors/', import.meta.url);
  await mkdir(vectorsDir, { recursive: true });
  await writeFile(new URL('mandate.json', vectorsDir), JSON.stringify(vector,
    (_name, value: unknown) => typeof value === 'bigint' ? value.toString() : value, 2) + '\n');

  const solidity = `// Generated by npm run vectors:regenerate. Public test data only.\n// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\nlibrary Phase1Vector {\n    address internal constant OWNER = ${vector.owner};\n    bytes32 internal constant ROOT = ${vector.root};\n    bytes32 internal constant DIGEST = ${vector.digest};\n    bytes internal constant SIGNATURE = hex"${vector.signature.slice(2)}";\n\n    struct Grant {\n        address owner;\n        uint256 chainId;\n        address sessionKey;\n        uint256 perTxLimit;\n        uint256 budget;\n        uint256 windowSeconds;\n        uint256 expiry;\n        uint256 nonce;\n    }\n\n    function grants() internal pure returns (Grant[] memory result) {\n        result = new Grant[](${grants.length});\n${grants.map((g, i) => `        result[${i}] = Grant(OWNER, ${g.chainId}, ${g.sessionKey}, ${g.perTxLimit}, ${g.budget}, ${g.windowSeconds}, ${g.expiry}, ${g.nonce});`).join('\n')}\n    }\n\n    function leaves() internal pure returns (bytes32[] memory result) {\n        result = new bytes32[](${grants.length});\n${vector.leaves.map((leaf, i) => `        result[${i}] = ${leaf};`).join('\n')}\n    }\n\n    function proof(uint256 index) internal pure returns (bytes32[] memory result) {\n${vector.proofs.map((proof, i) => `        if (index == ${i}) {\n            result = new bytes32[](${proof.length});\n${proof.map((node, j) => `            result[${j}] = ${node};`).join('\n')}\n            return result;\n        }`).join('\n')}\n        revert("Unknown grant");\n    }\n}\n`;
  const docsDir = new URL('../../docs/vectors/', import.meta.url);
  await mkdir(docsDir, { recursive: true });
  await writeFile(new URL('Phase1Vector.sol', docsDir), solidity);
  console.log('Regenerated public vectors; the dedicated test key remains only in .env.');
}

main().catch(() => {
  // Library exceptions may carry sensitive inputs; never log the error object.
  console.error('Vector regeneration failed. Check dependencies and local file permissions.');
  process.exitCode = 1;
});
